apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flux-kluctl-controller.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "flux-kluctl-controller.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "flux-kluctl-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flux-kluctl-controller.fullname" . }}-kluctldeployment-editor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "flux-kluctl-controller.fullname" . }}-kluctldeployment-editor-role
subjects:
  - kind: ServiceAccount
    name: {{ include "flux-kluctl-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flux-kluctl-controller.fullname" . }}-kluctldeployment-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "flux-kluctl-controller.fullname" . }}-kluctldeployment-viewer-role
subjects:
  - kind: ServiceAccount
    name: {{ include "flux-kluctl-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flux-kluctl-controller.fullname" . }}-reconciler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "flux-kluctl-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
