name: chartreleaser

on:
  push:
    branches:
      - main
    paths:
      - '**/Chart.yaml'

permissions:
  contents: write # needed to write releases

jobs:
  chartreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
